
version: '4.0'

actions:    
  generate_dataset_incidence:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_incidence.py
      --output output/dataset_incidence.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --diseases_list gout
    outputs:
      highly_sensitive:
        cohort: output/dataset_incidence.csv          

  generate_dataset_primary:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_primary.py 
      --output output/dataset_primary.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --primary_disease gout
      --diseases_list gout
      --comorbidities_list chd diabetes cva ckd hypertension depression heart_failure liver_disease transplant alcohol
      --disease_features_list tophi chronic_gout
      --events_list flare
      --admissions_list gout
      --bloods_list urate creatinine cholesterol hba1c
      --medications_list ult allopurinol allopurinol_high febuxostat febuxostat_high benzbromarone probenecid colchicine steroid nsaid diuretic sglt2 ace_arb
      --outpatients_list rheumatology
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        cohort: output/dataset_primary.csv         

  measures_dataset_gout_2016:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_dataset_gout_2016.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --diseases_list gout
      --measure_disease gout
      --measure_start_date "2016-07-01"
      --measure_intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_gout_2016.csv

  measures_dataset_gout_2017:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_dataset_gout_2017.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --diseases_list gout
      --measure_disease gout
      --measure_start_date "2017-07-01"
      --measure_intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_gout_2017.csv

  measures_dataset_gout_2018:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_dataset_gout_2018.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --diseases_list gout
      --measure_disease gout
      --measure_start_date "2018-07-01"
      --measure_intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_gout_2018.csv

  measures_dataset_gout_2019:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_dataset_gout_2019.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --diseases_list gout
      --measure_disease gout
      --measure_start_date "2019-07-01"
      --measure_intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_gout_2019.csv

  measures_dataset_gout_2020:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_dataset_gout_2020.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --diseases_list gout
      --measure_disease gout
      --measure_start_date "2020-07-01"
      --measure_intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_gout_2020.csv

  measures_dataset_gout_2021:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_dataset_gout_2021.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --diseases_list gout
      --measure_disease gout
      --measure_start_date "2021-07-01"
      --measure_intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_gout_2021.csv

  measures_dataset_gout_2022:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_dataset_gout_2022.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --diseases_list gout
      --measure_disease gout
      --measure_start_date "2022-07-01"
      --measure_intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_gout_2022.csv

  measures_dataset_gout_2023:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_dataset_gout_2023.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --diseases_list gout
      --measure_disease gout
      --measure_start_date "2023-07-01"
      --measure_intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_gout_2023.csv

  measures_dataset_gout_2024:
    run: ehrql:v1 generate-measures analysis/dataset_definition_incidence_measures.py
      --output output/measures/measures_dataset_gout_2024.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --diseases_list gout
      --measure_disease gout
      --measure_start_date "2024-07-01"
      --measure_intervals 12
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_gout_2024.csv

  incidence_cleaning:
    run: stata-mp:latest analysis/001_incidence_cleaning.do "gout" "2016-07-01" "2025-06-30"
    needs: [generate_dataset_incidence, measures_dataset_gout_2016, measures_dataset_gout_2017, measures_dataset_gout_2018, measures_dataset_gout_2019, measures_dataset_gout_2020, measures_dataset_gout_2021, measures_dataset_gout_2022, measures_dataset_gout_2023, measures_dataset_gout_2024]
    outputs:
      moderately_sensitive:
        log1: logs/incidence_cleaning.log   
        table1: output/tables/redacted_counts_*.csv
        
  incidence_graphs:
    run: stata-mp:latest analysis/002_incidence_graphs.do "gout" "2020-03-01"
    needs: [incidence_cleaning]
    outputs:
      moderately_sensitive:
        log1: logs/incidence_graphs.log
        table1: output/tables/arima_standardised.csv
        figure1: output/figures/inc_*.svg
        figure2: output/figures/prev_*.svg

  sarima:
    run: r:latest analysis/100_sarima.R "2020-03-01"
    needs: [incidence_graphs]
    outputs:
      moderately_sensitive:
        log1: logs/sarima_log.txt   
        figure1: output/figures/auto_residuals_*.png
        figure2: output/figures/obs_pred_*.png
        table1: output/tables/change_incidence_byyear.csv
  
  measures_practice_gout:
    run: ehrql:v1 generate-measures analysis/dataset_definition_practice_measures.py
      --output output/measures/measures_practice_gout.csv
      --
      --studystart_date "2016-07-01"
      --studyend_date "2025-06-30"
      --studyfup_date "2026-06-30"
      --diseases_list gout
      --measure_disease gout
      --measure_start_date "2016-07-01"
      --measure_intervals 1
    needs: [generate_dataset_incidence]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_practice_gout.csv

  cohort_cleaning:
    run: stata-mp:latest analysis/200_cohort_cleaning.do "gout" "2016-07-01" "2025-06-30" "2026-06-30" "2022-06-01" "agegroup|sex|ethnicity|imd|region" "chd|diabetes|cva|ckd|hypertension|depression|heart_failure|liver_disease|transplant|alcohol" "tophi|chronic_gout" "flare" "gout" "urate|creatinine|cholesterol|hba1c" "ult|allopurinol|allopurinol_high|febuxostat|febuxostat_high|benzbromarone|probenecid|colchicine|steroid|nsaid|diuretic|sglt2|ace_arb" "rheumatology"
    needs: [generate_dataset_primary, measures_practice_gout]
    outputs:
      highly_sensitive:
        log1: logs/cohort_cleaning.log   
        data1: output/data/cohort_processed.dta
        data2: output/data/flares_long.dta

  data_tables:
    run: stata-mp:latest analysis/300_data_tables.do "gout" "agegroup|sex|ethnicity|imd|region" "rheumatology"
    needs: [cohort_cleaning]
    outputs:
      moderately_sensitive:
        log1: logs/data_tables.log   
        table1: output/tables/data_table_*.csv

  summary_tables:
    run: stata-mp:latest analysis/400_summary_tables.do "gout" "chd|diabetes|cva|ckd|hypertension|depression|heart_failure|liver_disease|transplant|alcohol" "tophi|chronic_gout" "flare" "gout" "urate|creatinine|cholesterol|hba1c" "ult|allopurinol|allopurinol_high|febuxostat|febuxostat_high|benzbromarone|probenecid|colchicine|steroid|nsaid|diuretic|sglt2|ace_arb" "rheumatology"
    needs: [cohort_cleaning]
    outputs:
      moderately_sensitive:
        log1: logs/summary_tables.log   
        table1: output/tables/summary_table_*.csv

  temporal_plots:
    run: stata-mp:latest analysis/500_temporal_plots.do "gout" "agegroup|sex|ethnicity|imd|region" "2016-07-01" "2025-06-30" "2026-06-30" "2022-06-01"
    needs: [data_tables]
    outputs:
      moderately_sensitive:
        log1: logs/temporal_plots.log   
        figure1: output/figures/temporal_plot_*.svg

  logistic_models:
    run: stata-mp:latest analysis/600_logistic_models.do "gout"
    needs: [cohort_cleaning]
    outputs:
      moderately_sensitive:
        log1: logs/logistic_models.log   
        table1: output/tables/melogit_summary.csv
        table2: output/tables/logistic_summary.csv

  # survival_models:
  #   run: stata-mp:latest analysis/700_survival_models.do "gout" "2026-06-30"
  #   needs: [cohort_cleaning]
  #   outputs:
  #     moderately_sensitive:
  #       log1: logs/survival_models.log   
  #       table1: output/tables/landmark_cox_summary.csv
  #       figure1: output/figures/km_*.svg
  #       figure2: output/figures/loglog_*.svg

  generate_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/report.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [temporal_plots, incidence_graphs, sarima]
    outputs:
      moderately_sensitive:
        notebook: output/report.html                                
  